version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    ports:
      - '9092'
      - '19092'
    environment:
      ZOOKEEPER: zookeeper:2181
      ADVERTISED_LISTENER: 10.0.1.24
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock